### ISSUE TITLE
New gem release for Capybara compatibility

### ISSUE THREAD

**Issue by wincent** [langalex/culerity#10]
Any chance of cutting a new gem release soon? Culerity 0.2.3 doesn't work with Capybara, but the current HEAD of master (commit 218f6314460b6c350a5b6dbcb873d76a0bade92e) does work.

It would make using Capybara a bit easy if we could just do "sudo gem install culerity", but right now one has to clone the repo and build a custom version based on HEAD.

Cheers,
Wincent

**Comment by langalex** [comment]
0.2.4 is out

**Comment by wincent** [comment]
Thanks!
