### ISSUE TITLE
Culerity should only have development dependency on cucumber and rspec

### ISSUE THREAD

**Issue by aslakhellesoy** [langalex/culerity#12]
The Rakefile should have this:

<pre>
gem.add_development_dependency 'cucumber' 
gem.add_development_dependency 'rspec' 
</pre>

Otherwise people can't use Culerity unless they have both RSpec and Cucumber installed, and that shouldn't be a requirement. (I'm trying to verify that Cucumber+Culerity works in pure Test::Unit mode by uninstalling RSpec, and this hard dependency makes it hard for me to test that).

**Comment by langalex** [comment]
fixed in 0.2.6

**Comment by tpo** [comment]
This bug could be closed as well
