### ISSUE TITLE
Exception invoking jsxGet_length (Culerity::CulerityException

### ISSUE THREAD

**Issue by thirdreplicator** [langalex/culerity#19]
This is my first time using Culerity.  Celerity seems to be working by itself.  script/server -e test -p 3001 seems to be receiving the request, but then something bad happens:

[root@zvm trunk]# cucumber features/homepage.feature
Using the default profile...
WARNING: No DRb server is running. Running features locally:
/var/zvents/zvents/config/../vendor/rails/railties/lib/rails/gem_dependency.rb:119:Warning: Gem::Dependency#version_requirements is deprecated and will be removed on or after August 2010.  Use #requirement
.May 19, 2010 6:30:32 PM com.gargoylesoftware.htmlunit.IncorrectnessListenerImpl notify
WARNING: Expected content type of 'application/javascript' or 'application/ecmascript' for remotely loaded JavaScript element at 'http://connect.facebook.net/en_US/all.js', but got 'application/x-javascript'.
F-

(::) failed steps (::)

NativeException: com.gargoylesoftware.htmlunit.ScriptException: Exception invoking jsxGet_length (Culerity::CulerityException)
com/gargoylesoftware/htmlunit/javascript/JavaScriptEngine.java:527:in `run'
net/sourceforge/htmlunit/corejs/javascript/Context.java:537:in`call'
net/sourceforge/htmlunit/corejs/javascript/ContextFactory.java:538:in `call'
com/gargoylesoftware/htmlunit/javascript/JavaScriptEngine.java:457:in`callFunction'
com/gargoylesoftware/htmlunit/html/HtmlPage.java:910:in `executeJavaScriptFunctionIfPossible'
com/gargoylesoftware/htmlunit/javascript/host/EventListenersContainer.java:159:in`executeEventListeners'
com/gargoylesoftware/htmlunit/javascript/host/EventListenersContainer.java:216:in `executeBubblingListeners'
com/gargoylesoftware/htmlunit/javascript/host/Node.java:645:in`fireEvent'
com/gargoylesoftware/htmlunit/html/HtmlElement.java:887:in `run'
net/sourceforge/htmlunit/corejs/javascript/Context.java:537:in`call'
net/sourceforge/htmlunit/corejs/javascript/ContextFactory.java:538:in `call'
com/gargoylesoftware/htmlunit/html/HtmlElement.java:892:in`fireEvent'
com/gargoylesoftware/htmlunit/html/HtmlPage.java:1154:in `executeEventHandlersIfNeeded'
com/gargoylesoftware/htmlunit/html/HtmlPage.java:200:in`initialize'
com/gargoylesoftware/htmlunit/WebClient.java:427:in `loadWebResponseInto'
com/gargoylesoftware/htmlunit/WebClient.java:303:in`getPage'
com/gargoylesoftware/htmlunit/WebClient.java:376:in `getPage'
features/homepage.feature:10:in`When I am on the homepage'

Failing Scenarios:
cucumber features/homepage.feature:7 # Scenario: Visit homepage

**Comment by thirdreplicator** [comment]
Oh, and here is the feature file:

[root@zvm trunk]# more features/homepage.feature

> Feature: Make sure the homepage works
> 
> As anybody
> I should be able to go to the zvents.com homepage
> In order to see what events are in my area.
> 
> Scenario: Visit homepage
> 
> Given an anonymous user
> When I am on the homepage
> Then I should see "Home"

**Comment by langalex** [comment]
looks like a javascript exception. does the problem go away when you comment out all the javascript/remove script include tags?

**Comment by thirdreplicator** [comment]
Oh that's interesting.  I'll try that.  As a side note, capybara seems to digest the page okay, which is a bit hard to understand because it relies on Culerity.
