### ISSUE TITLE
Nailgun support

### ISSUE THREAD

**Issue by ashmoran** [langalex/culerity#20]
Currently JVM startup time makes for a very frustrating feedback loop when running Culerity over a small number of scenarios (often just one).  JRuby 1.5 has Nailgun support and I'd love to use this with Culerity!  It'd make a huge difference to a lot of features I work on.

**Comment by langalex** [comment]
i don't know anything about nailgun. how would you integrate it?

**Comment by ashmoran** [comment]
This page outlines the idea behind using it: http://blog.headius.com/2009/05/jruby-nailgun-support-in-130.html

You can also set the environment variable JRUBY_OPTS="--ng --fast" in Cucumber to trick Culerity into running against the Nailgun server.

But there's some sort of communication problem between the two and Culerity can't run the Celerity code it needs too.  Unfortunately, it's beyond my understanding of all the bits involved what's going wrong.

**Comment by mrship** [comment]
I played with this some more (I was pairing with Ashley when we reviewed it previously) and have now got it to work. You need to run jruby --ng-server as a background process and then pass --ng to the jruby process that runs the celerity_server. 

The way I ended up doing that was to pass JRUBY_OPTS ENV var when I run culerity through capybara.

Upshot is the culerity _already_ works with Nailgun - FTW!

(Of note, don't try and use --fast as well - that is what was breaking it for us. Plus, even if you then remove --fast the --ng-server instance of jruby is borked and you need to start a new one)

**Comment by langalex** [comment]
cool. maybe you can document this in the wiki so everyone can use this.

**Comment by mrship** [comment]
done!

**Comment by ashmoran** [comment]
I like the look of this! Can't wait to try it out :-)
