### ISSUE TITLE
"Then I should see..." steps fail if text is contained in paragraph tags and not div tags

### ISSUE THREAD

**Issue by davidcelis** [langalex/culerity#21]
When writing a simple test to create a user and log into the app, everything was working correctly until a "Then I should see..." step, which was looking for a flash notice saying "Login successful!" The step was failing, but physically logging into the app showed that the flash notice was definitely there, as did viewing the page's source at the time of logging in. On a whim, I changed the tags enclosing the notice from <p> tags to <div> tags, and the test passed.

I'm not sure why this would (or should) matter. Do "Then I should see..." steps fail with <p> tags? Do they fail with anything but <div> tags?

**Comment by langalex** [comment]
if you put a div around your entire html the <p> tags will start working again. the reason for this is that looking for a div allows that step to pick up dynamically (via javascript) inserted content. you can see this here: http://github.com/langalex/culerity/blob/master/rails_generators/culerity/templates/features/step_definitions/culerity_steps.rb (lin 148)

**Comment by mourdok** [comment]
Hello!

I managed to solve this problem of "I Should See" as follows:

http://twitter.com/mourdok/status/19861614119

I hope I have contributed

**Comment by langalex** [comment]
just for the record i'm repeating my comment under the gist: if you fork the repo and patch it yourself you will get the credit, if not i can just do it myself.... your choice.

**Comment by mourdok** [comment]
@langalex: I do a Fork. For as much use JRuby, I had to make some modifications to the Culerity legal work. Soon send you the link, as amended.
