### ISSUE TITLE
Doctype being removed

### ISSUE THREAD

**Issue by pollingj** [langalex/culerity#23]
When I use culerity to run javascript features in cucumber I've noticed it changes my HTML5 doctype to <?xml version="1.0" encoding="utf-8"?>

This is causing all my calls to validate the markup to fail.

**Comment by pollingj** [comment]
Actually, it looks like any DocType information is being removed fullstop

**Comment by langalex** [comment]
culerity doesn't do anything with doctypes, so i would guess this is a problem with [htmlunit](http://htmlunit.sourceforge.net/)

**Comment by pollingj** [comment]
I have looked a little further and it does appear the selenium has the same issue.  I may look into removing the html validation when running JS tests for the moment.
