### ISSUE TITLE
Culerity generators in Rails 3

### ISSUE THREAD

**Issue by cimm** [langalex/culerity#26]
Hi there,

I'm trying to run Culerity in Rails 3 (beta 4) but can't run the generators as `rails g` doesn't find any. This makes sense as the generator mechanism changed in Rails 3.

So I'm wondering, is Culerity Rails 3 compatible and am I missing something?

Thanks!

**Comment by langalex** [comment]
no, the generators would have to be rewritten. shouldn't be too hard though, want to give it a try?

**Comment by cimm** [comment]
Never looked at the Rails 3 generators in details so yes, could be interesting.

**Comment by cimm** [comment]
Apparently bbhoss has solved this problem, there is a pull request at http://github.com/langalex/culerity/pull/27
