### ISSUE TITLE
Broken pipe with RVM (or whatever)

### ISSUE THREAD

**Issue by phoet** [langalex/culerity#29]
i am trying to get rails cucumber tests working with rvm. i experimented with various versions of culerity, celertiy, cucumber and rails, but nothing seems to work...

maybee anybody has seen this:

[2010-09-23 23:37:40] ERROR Errno::EPIPE: Broken pipe
    /Users/nofail/.rvm/gems/ruby-1.8.7-p302@tolingo-site/gems/rails-2.3.4/lib/rails/rack/log_tailer.rb:30:in `write'
    /Users/nofail/.rvm/gems/ruby-1.8.7-p302@tolingo-site/gems/rails-2.3.4/lib/rails/rack/log_tailer.rb:30:in`print'
    /Users/nofail/.rvm/gems/ruby-1.8.7-p302@tolingo-site/gems/rails-2.3.4/lib/rails/rack/log_tailer.rb:30:in `tail_log'
    /Users/nofail/.rvm/gems/ruby-1.8.7-p302@tolingo-site/gems/rails-2.3.4/lib/rails/rack/log_tailer.rb:18:in`call'
    /Users/nofail/.rvm/gems/ruby-1.8.7-p302@tolingo-site/gems/rack-1.0.1/lib/rack/content_length.rb:13:in `call'
    /Users/nofail/.rvm/gems/ruby-1.8.7-p302@tolingo-site/gems/rack-1.0.1/lib/rack/handler/webrick.rb:50:in`service'

the only thing i found was a discussion on stackoverflow: http://stackoverflow.com/questions/3445002/error-errnoepipe-broken-pipe-with-culerity

this is the (j)ruby versions i use:
ruby 1.8.7 (2010-08-16 patchlevel 302) [i686-darwin10.4.0]
jruby 1.5.2 (ruby 1.8.7 patchlevel 249) (2010-08-20 1c5e29d) (Java HotSpot(TM) 64-Bit Server VM 1.6.0_20) [x86_64-java]

**Comment by phoet** [comment]
one more thing:

when i surf the page on localhost:3001 i get the same broken pipe errors in my browser, but after reloading the page the error is gone. this happens every second call?!

**Comment by phoet** [comment]
i did some more testing on versions of ruby and gems and i now pinned the problem:

broken pipe errors do NOT occur using OSX system ruby. i tried various versions of 1.8.7 and ree with RVM and i always got the broken pipe errors.

with system ruby there are no errors, BUT every second call will result in a blank page, which seems to be the same error, just different...

**Comment by phoet** [comment]
it seems that somehow the $stdout pipe goes away and the rails logging output can not be printed. maybe something with the log-file? less tries to open it as a binaray file:

  less log/culerity.log 
  "log/culerity.log" may be a binary file.  See it anyway?

i played around a little bit with rack/log_tailer.rb, in which the broken-pipe occurs and patched line 30 to rescue the output:

  $stdout.print(contents) rescue $stderr.print("error #{$!} with #{contents}")

now the logging-output goes into the console, which is way better than an error on every second request.

**Comment by simianarmy** [comment]
Thanks a million, phoet - that was driving me craaazy.  I tried OS X ports jruby, rvm install jruby, and jruby from source (latest), and got the same error each time.  Your fix solved the issue for me (still seeing the broken pipe error, but it's not causing all my tests to fail!)

**Comment by phoet** [comment]
maybee you should try steam https://github.com/svenfuchs/steam

**Comment by simianarmy** [comment]
Thanks phoet, will do.  I also ran into some issue with culerity running under the  development environment during browser navigation calls ($browser.goto) but under culerity otherwise..made it impossible to do simple session based testing, so right now just working with selenium.
