### ISSUE TITLE
RemoteObjectProxy implements method_missing but not respond_to?

### ISSUE THREAD

**Issue by jfirebaugh** [langalex/culerity#33]
`respond_to?` should always be implemented when `method_missing` is implemented.

Capybara needs to check if a given element responds to `checked?` or `selected?`, and right now will have to rescue NoMethodError instead of using `respond_to?`.

**Comment by jfirebaugh** [comment]
Actually it can't even rescue NoMethodError, Culerity::CulerityException is what's raised.

**Comment by langalex** [comment]
fixed in 0.2.14
