### ISSUE TITLE
culerity hangs on exit

### ISSUE THREAD

**Issue by ebertech** [langalex/culerity#34]
Hi

Here's the specs of what I'm running
ruby 1.8.7 
jruby 1.4.0 (ruby 1.8.7 patchlevel 174) (2009-11-02 69fbfa3) (Java HotSpot(TM) 64-Bit Server VM 1.6.0_22) [x86_64-java]
culerity 0.2.14

When the scenarios end cucumber hangs in the at_exit in culerity_steps on:

  $server.close if $server

I looked at the code and $server is the result of an IO.popen extened with the ServerCommands module but closing on an IO doesn't seem to make sense since it's still running. I changed it to   

$server.exit_server if $server

which sends the _exit_ command. Should this be changed in the generator? Am I the only one experiencing this sort of thing?

**Comment by langalex** [comment]
so, did the change fix your issue? if so, would you be willing to fork and make a pull request?

**Comment by ebertech** [comment]
I mean, sure, that's not a problem. It's just weird that no one else has experienced this.

**Comment by langalex** [comment]
thanks, pulled this in
