### ISSUE TITLE
Third party APIs

### ISSUE THREAD

**Issue by mattbeedle** [langalex/culerity#4]
I've just switched to culerity/celerity from webrat, and although it was a little painful to update all 200 scenarios it's almost all working except for one problem.  My app is using a third party payment provider, and I was stubbing out things like credit card valid, and the different responses before running certain scenarios.  Obviously this no longer works.  Is there any solution?

**Comment by duelinmarkers** [comment]
I would recommend you create alternate implementations of your classes for interacting with external services. These implementations can just return canned data. Then create a specific RAILS_ENV for running your Cucumber suite, and in the config/environments/foo.rb file for that env, load your alternate implementations. (You may also want to use them in the development environment.)

**Comment by langalex** [comment]
sounds like a good solution to me.
