### ISSUE TITLE
common_celerity_steps.rb doesn't emulate webrat_steps.rb fully

### ISSUE THREAD

**Issue by akahn** [langalex/culerity#7]
Culerity comes with the some handy steps like: 

```
When /I fill in "(.*)" with "(.*)"/ do |value, field|
  $browser.text_field(:id, find_label(field).for).set(value)
end
```

This allows users to use their existing features, which formerly ran in Webrat, in Celerity. 

However, Webrat's `fill_in` method accepts either the text of a form element's label _or_ a form element's `name` attribute. Culerity's version of this only accepts the text from the label. In order for common_celerity_steps.rb to truly stand in for webrat_steps.rb, these step definitions need to take either a label name or a form element's `name`.

The step in common_celerity_steps.rb would then look like:
    When /I fill in "(._)" with "(._)"/ do |value, field|
      begin
        $browser.text_field(:name, field).set(value)
      rescue Celerity::Exception::UnknownObjectException
        $browser.text_field(:id, find_label(field).for).set(value)
      end
    end

What are people's thoughts on this approach?

**Comment by langalex** [comment]
i nicer way might be to do this:

```
text_field = [:name, :id].map{|attribute| $browser.text_field(attribute, field)}.find(&:exist?) ||  raise('not found')
text_field.set(value)
```

this way you wouldn't have to rescue any exceptions. anyone wants to implement this?

**Comment by akahn** [comment]
This is definitely a cleaner approach. 

However, this would lose the original functionality of being able to specify a field by the field's label's text. 

Ideally, there would be an approach that can use `id`, `name`, or label's `text`. Any ideas?

**Comment by langalex** [comment]
```
text_field = [$browser.text_field(attribute, :id), $browser.text_field(attribute, :name), $browser.text_field($browser.label(attribute, :id).for, :id)].find(&:exist?) ||  raise('not found')
text_field.set(value)
```

**Comment by langalex** [comment]
maybe better:

```
text_field = [[attribute, :id], [attribute, :name], [$browser.label(attribute, :id).for, :id]].map{|_attribute, field| $browser.text_field(_attribute, field}.find(&:exist?) ||  raise('not found')
text_field.set(value)
```

**Comment by fuzziness** [comment]
refined (and working) version:

<pre><code>matchers = [[attribute, :id], [attribute, :name]]
matchers << [$browser.label(:id, attribute).for, :id] if $browser.label(:id, attribute).exist?
text_field = matchers.map{|field, matchter| $browser.text_field(matchter, field)}.find(&:exist?) ||  raise('not found')
text_field.set(value)
</code></pre>

**Comment by langalex** [comment]
looks great. now someone has to implement it :)

**Comment by langalex** [comment]
this is in 0.2.4
