### ISSUE TITLE
Can't find data created in previous step

### ISSUE THREAD

**Issue by akahn** [langalex/culerity#8]
Hi,

I'm having the issue described in the title, despite following the advice in the FAQ and having transactional fixtures turned off, etc. I describe my issue in more detail on the mailing list: http://groups.google.com/group/culerity-dev/browse_thread/thread/5c45242b7e994594 . Sorry to cross-post but I haven't had any progress on this. Thanks for any help. 

Alex

**Comment by langalex** [comment]
are you sure that your culerity process and your web process are using running in the same environment / use the same database?

**Comment by akahn** [comment]
Thanks for the advice. I'm not using culerity in any projects at the moment but I'll keep this in mind if I return to it. Thanks.
